### ISSUE TITLE
Herokuapp: Application error 

### ISSUE THREAD

**Issue by devpeskov** [Solexofficial/react-hotel_booking#3]
Здравствуйте, учу реакт и хотел поизучать исходники различных проектов, но не получается запустить локально (сайт выдает какие-то ошибки), а захосченная версия на herokuapp ведет себя так-же. Это какой-то баг или так и должно быть? Если баг, то не подскажите как исправить?

**Comment by Solexofficial** [comment]
Привет, спасибо за вопрос! heroku отключила с 28 ноября бесплатный хостинг.
Добавил инструкцию по запуску проекта локально в описании.
Дублирую:
```
cd client -> npm start
cd server -> npm run serve
change apiEndPoint -> client/config.json = {"apiEndPoint": "http://localhost:8080/api"}
```
Запускаем клиент, запускаем сервер, меняем ручку на локальный сервер.

**Comment by peskovdev** [comment]
Спасибо за ответ. Все получилось!
